import json

langs = {
    "en": {"profile_title": "📊 **HBD Business Profile**", "update_prompt": "👇 **What would you like to update?**", "update_label": "Update", "missing_reason": "is missing.", "change_reason": "Change your", "name": "Name", "category": "Category", "phone_number": "Phone Number", "address": "Address", "area": "Area", "city": "City", "state": "State", "website": "Website"},
    "hi": {"profile_title": "📊 **HBD बिजनेस प्रोफाइल**", "update_prompt": "👇 **आप क्या अपडेट करना चाहेंगे?**", "update_label": "अपडेट करें", "missing_reason": "मौजूद नहीं है।", "change_reason": "अपना बदलें", "name": "नाम", "category": "श्रेणी", "phone_number": "फ़ोन नंबर", "address": "पता", "area": "क्षेत्र", "city": "शहर", "state": "राज्य", "website": "वेબसाइट"},
    "gu": {"profile_title": "📊 **HBD બિઝનેસ પ્રોફાઇલ**", "update_prompt": "👇 **તમે શું અપડેટ કરવા માંગો છો?**", "update_label": "અપડેટ કરો", "missing_reason": "ખૂટે છે.", "change_reason": "તમારું બદલો", "name": "નામ", "category": "શ્રેણી", "phone_number": "ફોન નંબર", "address": "સરનામું", "area": "વિસ્તાર", "city": "શહેર", "state": "રાજ્ય", "website": "વેબસાઇટ"},
    "te": {"profile_title": "📊 **HBD వ్యాపార ప్రొఫైల్**", "update_prompt": "👇 **మీరు దేనిని అప్‌డేట్ చేయాలనుకుంటున్నారు?**", "update_label": "అప్‌డేట్ చేయండి", "missing_reason": "లేదు.", "change_reason": "మీ అప్‌డేట్ చేయండి", "name": "పేరు", "category": "వర్గం", "phone_number": "ఫోన్ నంబర్", "address": "చిరునామా", "area": "ప్రాంతం", "city": "నగరం", "state": "రాష్ట్రం", "website": "వెబ్‌సైట్"},
    "ta": {"profile_title": "📊 **HBD வணிக விவரம்**", "update_prompt": "👇 **நீங்கள் எதை மாற்ற விரும்புகிறீர்கள்?**", "update_label": "மாற்று", "missing_reason": "இல்லை.", "change_reason": "மாற்றவும்", "name": "பெயர்", "category": "வகை", "phone_number": "தொலைபேசி எண்", "address": "முகவரி", "area": "பகுதி", "city": "நகரம்", "state": "மாநிலம்", "website": "இணையதளம்"},
    "mr": {"profile_title": "📊 **HBD व्यवसाय प्रोफाइल**", "update_prompt": "👇 **तुम्हाला काय अपडेट करायचे आहे?**", "update_label": "अपडेट करा", "missing_reason": "उपलब्ध नाही.", "change_reason": "तुमची माहिती बदला", "name": "नाव", "category": "वर्ग", "phone_number": "फोन नंबर", "address": "पत्ता", "area": "क्षेत्र", "city": "शहर", "state": "राज्य", "website": "वेबसाइट"},
    "bn": {"profile_title": "📊 **HBD ব্যবসা প্রোফাইল**", "update_prompt": "👇 **আপনি কি আপডেট করতে চান?**", "update_label": "আপডেট করুন", "missing_reason": "নেই।", "change_reason": "আপনার পরিবর্তন করুন", "name": "নাম", "category": "বিভাগ", "phone_number": "ফোন নম্বর", "address": "ঠিকানা", "area": "এলাকা", "city": "শহর", "state": "রাজ্য", "website": "ওয়েবসাইট"},
    "kn": {"profile_title": "📊 **HBD ವ್ಯಾಪಾರ ವಿವರ**", "update_prompt": "👇 **ನೀವು ಏನನ್ನು ನವೀಕರಿಸಲು ಬಯಸುತ್ತೀರಿ?**", "update_label": "ನವೀಕರಿಸಿ", "missing_reason": "ಇಲ್ಲ.", "change_reason": "ನಿಮ್ಮ ಬದಲಿಸಿ", "name": "ಹೆಸರು", "category": "ವರ್ಗ", "phone_number": "ಫೋನ್ ಸಂಖ್ಯೆ", "address": "ವಿಳಾಸ", "area": "ಪ್ರದೇಶ", "city": "ನಗರ", "state": "ರಾಜ್ಯ", "website": "ವೆಬ್‌ಸೈಟ್"},
}

print(json.dumps(langs, indent=4, ensure_ascii=False))
########